name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug secrets
        run: |
          echo "Host is set: ${{ secrets.VM_HOST != '' }}"
          echo "User is set: ${{ secrets.VM_USER != '' }}"
          echo "Key is set: ${{ secrets.VM_SSH_KEY != '' }}"

      - name: Copy project files to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          source: ".,!Frontend/.env,!backend/.env"
          target: "/home/admin123/Real-time-walk-through-facial-recognition-attendance-system"

      - name: Deploy on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            cd /home/admin123/Real-time-walk-through-facial-recognition-attendance-system
            docker-compose down
            docker-compose up -d --build
            sudo systemctl restart backend.service
            docker-compose ps
            sudo systemctl status backend.service --no-pager
            docker image prune -f
